version: "3"
services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    # volumes:
    #   - "db:/var/lib/postgresql/data"
    environment:
      # - NODE_ENV=
      # - BACKEND_URL=http://localhost:8090
      # # - FRONTEND_URL=http://localhost:3000
      # - PROXY_PORT=443
      # - PORT=8090

      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

      # - DB_DIALECT=postgres
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=postgres
      # - DB_PASS=postgres
      # - DB_NAME=postgres

      # - JWT_SECRET=kZaOTd+YZpjRUyyuQUpigJaEMk4vcW4YOymKPZX0Ts8=
      # - JWT_REFRESH_SECRET=dBSXqFg9TaNUEDXVp6fhMTRLBysP+j2DSqf7+raxD3A=

      # - REDIS_URI=redis://:@127.0.0.1:6379
      # - REDIS_OPT_LIMITER_MAX=1
      # - REDIS_OPT_LIMITER_DURATION=3000

      # - USER_LIMIT=10000
      # - CONNECTIONS_LIMIT=100000
      # - CLOSED_SEND_BY_ME=true

      # - FACEBOOK_APP_ID=
      # - FACEBOOK_APP_SECRET=

      # - GERENCIANET_SANDBOX=false
      # - GERENCIANET_CLIENT_ID=
      # - GERENCIANET_CLIENT_SECRET=
      # - GERENCIANET_PIX_CERT=
      # - GERENCIANET_PIX_KEY=

      # - MAIL_HOST="smtp.gmail.com"
      # - MAIL_USER="seu-email"
      # - MAIL_PASS="senha-app-email"
      # - MAIL_FROM="seu-email"
      # - MAIL_PORT=587

      # - OPENAI_API_KEY=
  # api-service:
  #   build:
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8090:8090"
  #   restart: always
  #   volumes:
  #     - /node_modules
  #     # - "./api-service:/app"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - NODE_ENV=
  #     - BACKEND_URL=http://localhost:8090
  #     # - FRONTEND_URL=http://localhost:3000
  #     - PROXY_PORT=443
  #     - PORT=8090
